import chalk from 'chalk';

export async function helpCommand() {
  console.log(chalk.cyan('\n  Codra Code Commands:'));
  console.log(chalk.gray('  Authentication:'));
  console.log(chalk.gray('    /login                 Authenticate with Tera account'));
  console.log(chalk.gray('    /logout                Sign out and remove credentials'));
  console.log(chalk.gray('    /auth                  Show authentication status'));
  console.log('');
  console.log(chalk.gray('  General:'));
  console.log(chalk.gray('    /help                  Show this help message'));
  console.log(chalk.gray('    /status                Show project, provider, model, config status'));
  console.log(chalk.gray('    /doctor                Check system health and configuration'));
  console.log(chalk.gray('    /config                Show current configuration'));
  console.log(chalk.gray('    /clear                 Clear current session view'));
  console.log(chalk.gray('    /exit                  Quit Codra Code'));
  console.log('');
  console.log(chalk.gray('  Provider:'));
  console.log(chalk.gray('    /model [name]          Show or change current model'));
  console.log(chalk.gray('    /provider [name]       Show or change current provider'));
  console.log('');
  console.log(chalk.gray('  File Editing:'));
  console.log(chalk.gray('    /read <path>           Read a local file'));
  console.log(chalk.gray('    /read <path> --context Add file to context'));
  console.log(chalk.gray('    /write <path>          Create/update a file (with confirmation)'));
  console.log(chalk.gray('    /append <path>         Append content to file'));
  console.log(chalk.gray('    /patch <path>          Apply patch to file'));
  console.log(chalk.gray('    /diff <path>           Show file diff'));
  console.log(chalk.gray('    /pending               Show pending edits'));
  console.log(chalk.gray('    /apply                 Apply pending edits'));
  console.log(chalk.gray('    /discard               Discard pending edits'));
  console.log('');
  console.log(chalk.gray('  Git:'));
  console.log(chalk.gray('    /git                   Show git summary'));
  console.log(chalk.gray('    /git status            Show git status'));
  console.log(chalk.gray('    /git diff              Show git diff'));
  console.log(chalk.gray('    /git branch            Show git branches'));
  console.log(chalk.gray('    /git log               Show recent commits'));
  console.log(chalk.gray('    /git commit <msg>      Commit changes'));
  console.log('');
  console.log(chalk.gray('  Execution:'));
  console.log(chalk.gray('    /run <command>         Run shell command (with confirmation)'));
  console.log(chalk.gray('    /last                  Show last command result'));
  console.log('');
  console.log(chalk.gray('  Skills & Plugins:'));
  console.log(chalk.gray('    /skills                List installed skills'));
  console.log(chalk.gray('    /skill <name>          Activate a skill'));
  console.log(chalk.gray('    /skill clear           Clear active skill'));
  console.log(chalk.gray('    /plugins               List installed plugins'));
  console.log(chalk.gray('    /plugin <name>         Show plugin info'));
  console.log(chalk.gray('    /plugin run <name>     Run a plugin'));
  console.log('');
  console.log(chalk.gray('  MCP:'));
  console.log(chalk.gray('    /mcp                   List MCP servers'));
  console.log(chalk.gray('    /mcp status <name>     Check server status'));
  console.log(chalk.gray('    /mcp tools <name>      List server tools'));
  console.log(chalk.gray('    /mcp call <s> <t> <a>  Call a tool'));
  console.log('');
  console.log(chalk.gray('  Watching:'));
  console.log(chalk.gray('    /watch on              Start file watching'));
  console.log(chalk.gray('    /watch off             Stop file watching'));
  console.log(chalk.gray('    /watch status          Show watch status'));
  console.log('');
  console.log(chalk.gray('  Plans:'));
  console.log(chalk.gray('    /plan <task>           Create a new plan'));
  console.log(chalk.gray('    /plans                 List all plans'));
  console.log(chalk.gray('    /plan show <id>        Show plan details'));
  console.log(chalk.gray('    /plan approve <id>     Approve a plan'));
  console.log(chalk.gray('    /plan reject <id>      Reject a plan'));
  console.log(chalk.gray('    /plan run <id>         Run an approved plan'));
  console.log(chalk.gray('    /plan status <id>      Show plan status'));
  console.log('');
  console.log(chalk.gray('  Threads:'));
  console.log(chalk.gray('    /thread new <title>    Create a new thread'));
  console.log(chalk.gray('    /threads               List all threads'));
  console.log(chalk.gray('    /thread show <id>      Show thread details'));
  console.log(chalk.gray('    /thread resume <id>    Resume a thread'));
  console.log(chalk.gray('    /thread rename <id> <title>  Rename a thread'));
  console.log(chalk.gray('    /thread export <id>    Export thread'));
  console.log('');
  console.log(chalk.gray('  Context:'));
  console.log(chalk.gray('    /context               Show loaded instruction files'));
  console.log(chalk.gray('    /context files         List instruction files'));
  console.log(chalk.gray('    /context reload        Reload instruction files'));
  console.log('');
  console.log(chalk.gray('  Permissions:'));
  console.log(chalk.gray('    /permissions           Show permission policy'));
  console.log(chalk.gray('    /permissions set <level>  Set permission level'));
  console.log(chalk.gray('    /permissions allow <tool>  Allow a tool'));
  console.log(chalk.gray('    /permissions reset     Reset to defaults'));
  console.log('');
  console.log(chalk.gray('  Activity:'));
  console.log(chalk.gray('    /activity              Show activity summary'));
  console.log(chalk.gray('    /activity today        Today\'s activity'));
  console.log(chalk.gray('    /activity week         This week\'s activity'));
  console.log(chalk.gray('    /activity export       Export activity'));
  console.log('');
  console.log(chalk.gray('  Tool Calls:'));
  console.log(chalk.gray('    /tools log             Show recent tool calls'));
  console.log(chalk.gray('    /tools recent          Show recent tool calls'));
  console.log(chalk.gray('    /tools show <id>       Show tool call details'));
  console.log(chalk.gray('    /tools thread <id>     Show tool calls for thread'));
  console.log(chalk.gray('    /tools clear           Clear tool call logs'));
  console.log('');
  console.log(chalk.gray('  Sessions:'));
  console.log(chalk.gray('    /sessions              List saved sessions'));
  console.log(chalk.gray('    /session               Show current session info'));
  console.log(chalk.gray('    /save                  Force save current session'));
  console.log('');
}
